# Generated by Django 4.1 on 2022-08-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bienes',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
