# Generated by Django 4.1 on 2022-08-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
